cmake_minimum_required(VERSION 3.13)

add_executable(
  UTEST_ImageRecordUrlAndPathHelper
  UTEST_ImageRecordUrlAndPathHelper.cpp
  ${CMAKE_SOURCE_DIR}/src/helpers/ImageRecordUrlAndPathHelper.cpp
  ${IADE_CURL_SRC}
)

target_include_directories(
  UTEST_ImageRecordUrlAndPathHelper
  PRIVATE ${GENERAL_MOCKS_ROOT}/log
  PRIVATE ${CMAKE_SOURCE_DIR}
)

target_link_libraries(
  UTEST_ImageRecordUrlAndPathHelper
  GTest::gtest_main GTest::gmock
  ${IMAGES_ANNOTATOR_DATA_DRIVERS_TARGET} CURL::libcurl
)

include(GoogleTest)

gtest_add_tests(
  TARGET UTEST_ImageRecordUrlAndPathHelper
  TEST_SUFFIX .noArgs
  TEST_LIST noArgsTests
)

set_tests_properties(${noArgsTests} PROPERTIES TIMEOUT 600)
